oms:
  env: prod
  ####### MongoDB properties(Non-core configuration properties)  #######
  ####### delete mongodb config to disable mongodb #######
  mongodb:
    enable: false
  ####### Resource cleaning properties #######
  instanceinfo:
    retention: 1
  container:
    retention:
      local: 1
      remote: -1
  instance:
    metadata:
      cache:
        size: 1024
  accurate:
    select:
      server:
        percentage: 50
####### DingTalk properties(Non-core configuration properties) #######
####### Delete the following code to disable the DingTalk #######
#  alarm:
#    ding:
#      app-key: dingauqwkvxxnqskknfv
#      app-secret=XWrEPdAZMPgJeFtHuL0LH73LRj-74umF2_0BFcoXMfvnX0pCQvt0rpb1JOJU_HLl
#      agent-id=847044348

spring:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/btbox-boot?useUnicode
      username: root
      password: root
      maximum-pool-size: 20
      minimum-idle: 5
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-host-type: IP
        username: btbox
        password: 123456
  ####### Email properties(Non-core configuration properties) #######
  ####### Delete the following code to disable the mail #######
#  mail:
#    host: smtp.163.com
#    username: zqq@163.com
#    password: GOFZPNARMVKCGONV
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true