server:
  port: "7700"
spring:
  application:
    name: btbox-boot-powerjob
  profiles:
    active: "@profiles.active@"
  main:
    banner-mode: log
  jpa:
    open-in-view: "false"
  data:
    mongodb:
      repositories:
        type: none
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 209715200
      max-request-size: 209715200
logging:
  level:
    org:
      mongodb: warn
    tech:
      powerjob:
        server: warn
    MONITOR_LOGGER_DB_OPERATION: warn
    MONITOR_LOGGER_WORKER_HEART_BEAT: warn
  config: classpath:logback-plus.xml

###### PowerJob transporter configuration  ######
oms:
  transporter:
    active:
      protocols: AKKA,HTTP
    main:
      protocol: HTTP
  akka:
    port: "10086"
  http:
    port: "10010"
  table-prefix: pj_
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      # 监控的基础路径默认 actuator
#      base-path: /myactuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/btbox-powerjob-server.log
    prometheus:
      enabled: true
  health:
    mongo:
      enabled: ${oms.mongodb.enable}